#!/usr/bin/env python3

from bs4 import BeautifulSoup
from pathlib import Path
import logging
import pprint
import re
import sys
import urllib.request

class imdb2filename:
    def __init__(self, url, ext):
        self.url = url
        self.ext = (".%s" % (ext)) if ext is not None else ''
        self.year = None

    def fetch_and_parse(self):
        local_file = Path('kiname-input.html')
        if local_file.is_file():
            with local_file.open('r', -1, 'utf-8') as myfile:
                self.page = myfile.read()
                self.parse()
            return

        req = urllib.request.Request(self.url)
        req.add_header('User-Agent', "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3205.0 Safari/537.36")
        req.add_header('Accept-Language', 'en-US,en;q=0.8,pt;q=0.6')
        fn = ""
        with urllib.request.urlopen(req) as response:
            self.page = response.read()
            self.parse()

    def parse(self):
        soup = BeautifulSoup(self.page, 'html.parser')
        title_block = soup.find("div", class_="title_wrapper")
        year_block = title_block.h1.a
        self.year = year_block.text if year_block else None

        logging.debug("%s" % pprint.pformat(title_block.encode('utf-8')))
        logging.debug("Found title:<%s>" % title_block.encode('utf-8'))

        self.title = re.search('^<[^<>]+>([^<>]+)\u00A0\s*<', str(title_block.h1)).group(1)
        logging.debug("%s" % urllib.parse.quote(self.title))

        original_title_block = title_block.find('div',class_='originalTitle')
        match = re.search('^<[^<>]+>([^<>]+)<', str(original_title_block))
        self.original_title = match.group(1) if match else None

    def make_file_name(self):
        self.fetch_and_parse()
        title = self.original_title if self.original_title is not None else self.title
        year = ""
        if self.year is not None:
            year = " (%s)" % self.year
        fn = '"%s%s%s"' % (title, year, self.ext)
        return fn.encode('utf-8')

def main():
    if len(sys.argv) >= 3:
        logging.basicConfig(level=logging.DEBUG)
    if len(sys.argv) >= 2:
        url = sys.argv[1]
        ext = sys.argv[2] if len(sys.argv) > 2 else None
        k = imdb2filename(url, ext)
        fn = k.make_file_name()
        print("Plex recommended file name:\n%s" % fn)
    else:
        print("Usage:\n\t%s URL extension" % (sys.argv[0]))
    

if __name__ == "__main__":
    main()

